/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;

/**
 *
 * @author jamal
 */
public class MainjFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainjFrame
     */
    public MainjFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        labellastName = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        labelemail = new javax.swing.JLabel();
        labelphonenumber = new javax.swing.JLabel();
        lasNameTextfield = new javax.swing.JTextField();
        ageTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userLabel.setText("User");
        jPanel1.add(userLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 37, -1));

        labelName.setText("First Name");
        jPanel1.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));
        jPanel1.add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 130, -1));

        labellastName.setText("Last Name");
        jPanel1.add(labellastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 110, -1));

        labelGender.setText("Gender");
        jPanel1.add(labelGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 90, -1));

        labelAge.setText("Age");
        jPanel1.add(labelAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, -1));

        labelemail.setText("Email");
        jPanel1.add(labelemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 37, -1));

        labelphonenumber.setText("Phone Number");
        jPanel1.add(labelphonenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, -1));
        jPanel1.add(lasNameTextfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 130, -1));
        jPanel1.add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 140, -1));
        jPanel1.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 140, -1));
        jPanel1.add(phoneTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 140, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, -1, -1));

        jRadioButton1.setText("Male");
        jRadioButton1.setActionCommand("M");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jRadioButton2.setText("Female");
        jRadioButton2.setActionCommand("F");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String firstname;
        String lastname;
        String gender;
        String phonenumber;
        String email;
        int age;

        firstname = this.nameTextField.getText();
        lastname = this.lasNameTextfield.getText();
        gender = this.buttonGroup1.getSelection().getActionCommand();
        phonenumber = this.phoneTextField.getText();
        email = this.emailTextField.getText();
        age = Integer.parseInt(this.ageTextField.getText());

        System.out.println(firstname);
        System.out.println(lastname);
        System.out.println(gender);
        System.out.println(age);
        System.out.println(phonenumber);
        System.out.println(email);

        try{

            if(firstname.isBlank()){
                JOptionPane.showMessageDialog(rootPane, "Please ENTER firstname","OOPS", JOptionPane.HEIGHT);

            }else if (lastname.isBlank()){
                JOptionPane.showMessageDialog(rootPane,"Please enter last name" + lastname, "OOPS!",HEIGHT);
            }else if(email.isBlank()){
                JOptionPane.showMessageDialog(rootPane,"Please enter Email" + email, "oops!",HEIGHT);
            }else if(phonenumber.isBlank()){
                JOptionPane.showMessageDialog(rootPane,"Please enter phone number" + phonenumber,"oops",HEIGHT);
            }else if(gender.isBlank()){
                JOptionPane.showMessageDialog(rootPane,"Please select Gender" + gender,"oops",HEIGHT);
            }else if(age<18){
                JOptionPane.showMessageDialog(rootPane,"ONLY ABOVE 18" ,"oops",HEIGHT);
            }else{
                JOptionPane.showMessageDialog(rootPane,"SUCCESSFULY ADDAED"+ firstname ,"Success",HEIGHT);
            }
        } catch(NullPointerException npe){
            JOptionPane.showMessageDialog(rootPane,"select gender","Error",HEIGHT);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane,"enter age","Error",HEIGHT);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainjFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainjFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelemail;
    private javax.swing.JLabel labellastName;
    private javax.swing.JLabel labelphonenumber;
    private javax.swing.JTextField lasNameTextfield;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
