/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;

/**
 *
 * @author jamal
 */
public class FormJPanel extends javax.swing.JPanel {
    JPanel bottomPanel;
    ImageIcon picture;

    /**
     * Creates new form FormJPanel
     */
    public FormJPanel() {
        initComponents();
    }
 public FormJPanel(JPanel bottomPanel){
     initComponents();
     this.bottomPanel = bottomPanel;
     
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameTextFeild = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextfield = new javax.swing.JTextField();
        genderLabel = new javax.swing.JLabel();
        genderCombobox = new javax.swing.JComboBox<>();
        telephoneLabel = new javax.swing.JLabel();
        telephoneTextfield = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextfield = new javax.swing.JTextField();
        ageLabel = new javax.swing.JLabel();
        hobbiesLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hobbiesTextarea = new javax.swing.JTextArea();
        submitButton = new javax.swing.JButton();
        ageTextfield = new javax.swing.JTextField();
        imageButton = new javax.swing.JButton();
        uploadImageLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel1.setText("User Profile");

        nameLabel.setText("First Name");

        lastNameLabel.setText("Last Name");

        lastNameTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextfieldActionPerformed(evt);
            }
        });

        genderLabel.setText("Gender");

        genderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderCombobox.setSelectedIndex(-1);

        telephoneLabel.setText("Telephone");

        emailLabel.setText("Email");

        ageLabel.setText("Age");

        hobbiesLabel.setText("Hobbies :");

        hobbiesTextarea.setColumns(20);
        hobbiesTextarea.setRows(5);
        jScrollPane1.setViewportView(hobbiesTextarea);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        imageButton.setText("Select Image");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        uploadImageLabel.setText("Upload Image");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(hobbiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(uploadImageLabel))
                                .addGap(3, 3, 3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(submitButton)
                                .addGap(48, 48, 48)))
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(imageButton)))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastNameLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(telephoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE))
                                        .addComponent(genderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(72, 72, 72)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailTextfield)
                                        .addComponent(telephoneTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(genderCombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(154, 154, 154)
                            .addComponent(jLabel1)))
                    .addContainerGap(319, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(imageButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hobbiesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(uploadImageLabel)))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(nameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameLabel)
                        .addComponent(lastNameTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderLabel)
                        .addComponent(genderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telephoneLabel)
                        .addComponent(telephoneTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailLabel)
                        .addComponent(emailTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(282, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextfieldActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        User userObject = new User();

        try
        {

            //name = this.nameTextFeild.getText();
            userObject.setName(this.nameTextFeild.getText());
            //lastName = this.lastNameTextfield.getText();
            userObject.setLastName(this.lastNameTextfield.getText());
            //gender = this.genderCombobox.getSelectedItem().toString();
            userObject.setGender(this.genderCombobox.getSelectedItem().toString());
            //telephone = this.telephoneTextfield.getText();
            userObject.setTelephone(this.telephoneTextfield.getText());
            //email = this.emailTextfield.getText();
            userObject.setEmail(this.emailTextfield.getText());
            //age = Integer.parseInt(this.ageTextfield.getText());
            userObject.setAge(Integer.parseInt(this.ageTextfield.getText()));
            //hobbies = this.hobbiesTextarea.getText();
            userObject.setHobbies(this.hobbiesTextarea.getText());
            userObject.setPicture(this.picture);
            

            System.out.println(userObject.getName());
            System.out.println(userObject.getLastName());
            System.out.println(userObject.getGender());
            System.out.println(userObject.getTelephone());
            System.out.println(userObject.getEmail());
            System.out.println(userObject.getAge());
            System.out.println(userObject.getHobbies());
            System.out.println(userObject);

            if(userObject.getName().isBlank()){
                JOptionPane.showMessageDialog(this,"Please Enter Name", "OOPS",HEIGHT);
            }
            else if(userObject.getName().isBlank()){
                JOptionPane.showMessageDialog(this,"Please Enter last name" + userObject.getName(), "OOPS", HEIGHT);
            }
            else if(userObject.getEmail().isBlank()){
                JOptionPane.showMessageDialog(this,"Please Enter email" + userObject.getEmail(), "OOPS",HEIGHT);
            }
            else if(userObject.getGender().isBlank()){
                JOptionPane.showMessageDialog(this,"Please Select gender" + userObject.getGender(), "OOPS",HEIGHT);
            }
            else if(userObject.getAge()<18){
                JOptionPane.showMessageDialog(this,"ONLY ABOVE 18", "OOPS",HEIGHT);
            }
            else if(userObject.getHobbies().isBlank()){
                JOptionPane.showMessageDialog(this, "Please Input hobbies" + userObject.getHobbies(), "OPPS", HEIGHT);
            }
            else{JOptionPane.showMessageDialog(this,"SUCCESSFULLY ADDED " + userObject.getName() ,"success",HEIGHT,this.picture);
            ViewJPanel viewJPanelObject = new ViewJPanel(userObject);
            this.bottomPanel.add(viewJPanelObject);
            CardLayout layout =(CardLayout) this.bottomPanel.getLayout();
        layout.next(bottomPanel);

            }
        }catch(NullPointerException npe){
            JOptionPane.showMessageDialog(this, "select gender", "Error",HEIGHT);
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(this, "enter age","Error",HEIGHT);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_submitButtonActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
        
        //photo upload logic
JFileChooser file = new JFileChooser();
if (file.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
try {
BufferedImage img = ImageIO.read(file.getSelectedFile());
Image edited_image = img.getScaledInstance(60, 80,
Image.SCALE_SMOOTH);
if (edited_image != null) {
imgLabel.setText(file.getSelectedFile().getAbsolutePath());
 this.picture = new ImageIcon(edited_image);
imgLabel.setIcon(picture);

//ithis.userInfo.setPic(new ImageIcon(edited_image));
}
} catch (Exception ex) {
JOptionPane.showMessageDialog(this, "Please upload image correctly.", "Error - Incorrect image", JOptionPane.ERROR_MESSAGE);
ex.printStackTrace();
}
}
    }//GEN-LAST:event_imageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JTextField ageTextfield;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextfield;
    private javax.swing.JComboBox<String> genderCombobox;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobbiesLabel;
    private javax.swing.JTextArea hobbiesTextarea;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel imgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextfield;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextFeild;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel telephoneLabel;
    private javax.swing.JTextField telephoneTextfield;
    private javax.swing.JLabel uploadImageLabel;
    // End of variables declaration//GEN-END:variables
}
